class Solution:
    def grayCode(self, n: int) -> List[int]:
        if n == 0:
            return [0]
        else:
            # the graycode sequence is generated by looking at the mirror of the
            # first half of the greyCode array, reversing its order, and adding
            # each of those reversed values to 2^(n-1)
            firstHalf = self.grayCode(n-1)
            secondHalf = [i+2**(n-1) for i in firstHalf[::-1]]
            results = firstHalf + secondHalf
            return results
